### ISSUE TITLE
BatchTaskTest.importTest and BatchTaskTest.testUnresolvable have errors

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-lab#91]
The tests org.dkpro.lab.task.BatchTaskTest.importTest and org.dkpro.lab.task.BatchTaskTest.testUnresolvable produce errors when run with **mvn test** goal. The error message is as follows:

```
importTest(org.dkpro.lab.task.BatchTaskTest)  Time elapsed: 0.106 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.RuntimeException> but was <org.dkpro.lab.engine.ExecutionException>
```

```
testUnresolvable(org.dkpro.lab.task.BatchTaskTest)  Time elapsed: 0.072 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.RuntimeException> but was<org.dkpro.lab.engine.ExecutionException>
```

However the tests pass successfully when executed in Eclipse. After changing the expected exception type for these two tests to `org.dkpro.lab.engine.ExecutionException` the issue is fixed in maven build but then Eclipse will produce errors when running the tests.

**Comment by maxxkia** [comment]
I paste part of the stack trace for this error:

`Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.309 sec <<< FAILURE! - in org.dkpro.lab.task.BatchTaskTest
importTest(org.dkpro.lab.task.BatchTaskTest)  Time elapsed: 0.109 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.RuntimeException> but was<org.dkpro.lab.engine.ExecutionException>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine.executeConfiguration(MultiThreadBatchTaskEngine.java:170)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
	at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
	at org.dkpro.lab.Lab.run(Lab.java:107)
	at org.dkpro.lab.task.BatchTaskTest.importTest(BatchTaskTest.java:91)
Caused by: org.dkpro.lab.storage.UnresolvedImportException: Unable to resolve key [DATA] of task [org.dkpro.lab.task.BatchTaskTest$2] pointing to [task-latest://org.dkpro.lab.task.BatchTaskTest$1/DATA1]: Key not found
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:143)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine$ExecutionThread.run(MultiThreadBatchTaskEngine.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by maxxkia** [comment]
stack trace for error in testUnresolvable:

`testUnresolvable(org.dkpro.lab.task.BatchTaskTest)  Time elapsed: 0.07 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.RuntimeException> but was<org.dkpro.lab.engine.ExecutionException>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine.executeConfiguration(MultiThreadBatchTaskEngine.java:170)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
	at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
	at org.dkpro.lab.Lab.run(Lab.java:107)
	at org.dkpro.lab.task.BatchTaskTest.testUnresolvable(BatchTaskTest.java:221)
Caused by: org.dkpro.lab.storage.UnresolvedImportException: Unable to resolve import of task [org.dkpro.lab.task.BatchTaskTest$8] pointing to [task-latest://org.dkpro.lab.task.BatchTaskTest$7/DUMMY]; nested exception is org.dkpro.lab.storage.TaskContextNotFoundException: Task [org.dkpro.lab.task.BatchTaskTest$7] has never been executed.
	at org.dkpro.lab.engine.impl.BatchTaskEngine$ScopedTaskContext.resolve(BatchTaskEngine.java:521)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:141)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine$ExecutionThread.run(MultiThreadBatchTaskEngine.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.dkpro.lab.storage.TaskContextNotFoundException: Task [org.dkpro.lab.task.BatchTaskTest$7] has never been executed.
	at org.dkpro.lab.engine.impl.ImportUtil.createContextNotFoundException(ImportUtil.java:124)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.getLatestExecution(BatchTaskEngine.java:306)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.access$000(BatchTaskEngine.java:64)
	at org.dkpro.lab.engine.impl.BatchTaskEngine$ScopedTaskContext.resolve(BatchTaskEngine.java:518)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:141)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine$ExecutionThread.run(MultiThreadBatchTaskEngine.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by reckart** [comment]
@maxxkia I have committed a change which I hope fixes the problem for you. I think it was due to the random order in which the tests are executed that we hit this problem sometimes but not always. Can you try rebuilding now on the command line?

**Comment by maxxkia** [comment]
You pushed this change to develop branch, could you also push to master? Or should I switch to develop?

**Comment by reckart** [comment]
Switch to develop for testing. If it works, we can merge all into master.

**Comment by maxxkia** [comment]
Same error still persists:

`importTest(org.dkpro.lab.task.BatchTaskTest)  Time elapsed: 0.104 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.RuntimeException> but was<org.dkpro.lab.engine.ExecutionException>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine.executeConfiguration(MultiThreadBatchTaskEngine.java:170)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
	at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
	at org.dkpro.lab.Lab.run(Lab.java:107)
	at org.dkpro.lab.task.BatchTaskTest.importTest(BatchTaskTest.java:91)
Caused by: org.dkpro.lab.storage.UnresolvedImportException: Unable to resolve key [DATA] of task [org.dkpro.lab.task.BatchTaskTest$2] pointing to [task-latest://org.dkpro.lab.task.BatchTaskTest$1/DATA1]: Key not found
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:143)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.MultiThreadBatchTaskEngine$ExecutionThread.run(MultiThreadBatchTaskEngine.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by reckart** [comment]
For whatever reason, it seems I can reproduce it now. At least I get this stack trace also now when I build on the command line... odd.

**Comment by reckart** [comment]
No, getting other trace...

```
=== testUnresolvable =====================
2016-03-23 16:43:46 ERROR [main] (DefaultLoggingService) - [DefaultBatchTask-0771742d-f10e-11e5-b00e-fb7bcc5cb602] Task failed [org.dkpro.lab.task.impl.DefaultBatchTask](caused by TaskContextNotFoundException: Task [org.dkpro.lab.task.impl.MultiThreadBatchTaskTest$8] has never been executed.)
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.685 sec <<< FAILURE! - in org.dkpro.lab.task.impl.MultiThreadBatchTaskTest
importTest(org.dkpro.lab.task.impl.MultiThreadBatchTaskTest)  Time elapsed: 0.163 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.dkpro.lab.engine.ExecutionException> but was<org.dkpro.lab.storage.UnresolvedImportException>
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:143)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.runNewExecution(BatchTaskEngine.java:329)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.executeConfiguration(BatchTaskEngine.java:234)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
	at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
	at org.dkpro.lab.Lab.run(Lab.java:107)
	at org.dkpro.lab.task.impl.MultiThreadBatchTaskTest.importTest(MultiThreadBatchTaskTest.java:115)

testUnresolvable(org.dkpro.lab.task.impl.MultiThreadBatchTaskTest)  Time elapsed: 0.14 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.dkpro.lab.engine.ExecutionException> but was<org.dkpro.lab.storage.UnresolvedImportException>
	at org.dkpro.lab.engine.impl.ImportUtil.createContextNotFoundException(ImportUtil.java:124)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.getLatestExecution(BatchTaskEngine.java:306)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.access$000(BatchTaskEngine.java:64)
	at org.dkpro.lab.engine.impl.BatchTaskEngine$ScopedTaskContext.resolve(BatchTaskEngine.java:518)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.resolveImports(DefaultTaskContextFactory.java:141)
	at org.dkpro.lab.engine.impl.DefaultTaskContextFactory.createContext(DefaultTaskContextFactory.java:97)
	at org.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:46)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.runNewExecution(BatchTaskEngine.java:329)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.executeConfiguration(BatchTaskEngine.java:234)
	at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
	at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
	at org.dkpro.lab.Lab.run(Lab.java:107)
	at org.dkpro.lab.task.impl.MultiThreadBatchTaskTest.testUnresolvable(MultiThreadBatchTaskTest.java:249)
``

**Comment by reckart** [comment]
@maxxkia when you have the opportunity, can you please check if the build still fails for you?

**Comment by maxxkia** [comment]
@reckart build succeeded. will close the issue.
